// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteOrdering.Models;

#nullable disable

namespace WebsiteOrdering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613080514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.CategoryViewModel", b =>
                {
                    b.Property<string>("IDLOAIMONAN")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IDLOAIMAN_CHA")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TENLOAIMONAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDLOAIMONAN");

                    b.ToTable("LOAIMONAN", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ChiNhanhViewModel", b =>
                {
                    b.Property<string>("IDCHINHANH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DIACHICN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENCHINHANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCHINHANH");

                    b.ToTable("CHINHANH", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ChitietDHangViewModel", b =>
                {
                    b.Property<string>("IDDONHANG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DonHangViewModelIDDONHANG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GHICHU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GIADH")
                        .HasColumnType("int");

                    b.Property<string>("IDDEBANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KIEUPIZZA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<int>("TONGTIEN")
                        .HasColumnType("int");

                    b.HasKey("IDDONHANG", "IDMONAN");

                    b.HasIndex("DonHangViewModelIDDONHANG");

                    b.HasIndex("IDDEBANH");

                    b.HasIndex("IDMONAN");

                    b.HasIndex("IDSIZE");

                    b.ToTable("CHITIETDONHANG", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ChitietToppingViewModel", b =>
                {
                    b.Property<string>("IDTOPING")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDDONHANG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDTOPING", "IDDONHANG", "IDMONAN");

                    b.HasIndex("IDDONHANG", "IDMONAN");

                    b.ToTable("CHITIETTOPPING", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.DeBanhViewModel", b =>
                {
                    b.Property<string>("IDDEBANH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GIADEBANH")
                        .HasColumnType("int");

                    b.Property<string>("TENDEBANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDEBANH");

                    b.ToTable("DEBANH", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.DonHangViewModel", b =>
                {
                    b.Property<string>("IDDONHANG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDCHINHANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDDATBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAYDAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("PHUONGTHUCTHANHTOAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SONGUOI")
                        .HasColumnType("int");

                    b.Property<string>("TENKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TONGDH")
                        .HasColumnType("int");

                    b.HasKey("IDDONHANG");

                    b.HasIndex("IDCHINHANH");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ListGiaSizeViewModel", b =>
                {
                    b.Property<string>("IDLOAIMONAN")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IDSIZE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GIASIZE")
                        .HasColumnType("int");

                    b.Property<string>("ProductsViewModelIDMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SizeViewModelIDSIZE")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDLOAIMONAN", "IDSIZE");

                    b.HasIndex("IDSIZE");

                    b.HasIndex("ProductsViewModelIDMONAN");

                    b.HasIndex("SizeViewModelIDSIZE");

                    b.ToTable("LISTGIASIZE", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ProductsViewModel", b =>
                {
                    b.Property<string>("IDMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ANHMONAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GIAMONAN")
                        .HasColumnType("int");

                    b.Property<string>("IDLoaiMonAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENMONAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANGTHAIMAN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMONAN");

                    b.HasIndex("IDLoaiMonAn");

                    b.ToTable("MONAN", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.SizeViewModel", b =>
                {
                    b.Property<string>("IDSIZE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TENSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSIZE");

                    b.ToTable("SIZE", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ToppingViewModel", b =>
                {
                    b.Property<string>("IDTOPPING")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryViewModelIDLOAIMONAN")
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("GIATOPPING")
                        .HasColumnType("int");

                    b.Property<string>("IDLOAIMONAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ProductsViewModelIDMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TENTOPPING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTOPPING");

                    b.HasIndex("CategoryViewModelIDLOAIMONAN");

                    b.HasIndex("IDLOAIMONAN");

                    b.HasIndex("ProductsViewModelIDMONAN");

                    b.ToTable("TOPPING", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ChitietDHangViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.DonHangViewModel", null)
                        .WithMany("chitietdh")
                        .HasForeignKey("DonHangViewModelIDDONHANG");

                    b.HasOne("WebsiteOrdering.ViewModels.DeBanhViewModel", "DeBanh")
                        .WithMany()
                        .HasForeignKey("IDDEBANH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.DonHangViewModel", "DonHang")
                        .WithMany()
                        .HasForeignKey("IDDONHANG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.ProductsViewModel", "Product")
                        .WithMany()
                        .HasForeignKey("IDMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.SizeViewModel", "Size")
                        .WithMany()
                        .HasForeignKey("IDSIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeBanh");

                    b.Navigation("DonHang");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ChitietToppingViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.ToppingViewModel", "Topping")
                        .WithMany()
                        .HasForeignKey("IDTOPING")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.ChitietDHangViewModel", "chitietdhang")
                        .WithMany()
                        .HasForeignKey("IDDONHANG", "IDMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topping");

                    b.Navigation("chitietdhang");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.DonHangViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.ChiNhanhViewModel", "chinhanh")
                        .WithMany()
                        .HasForeignKey("IDCHINHANH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chinhanh");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ListGiaSizeViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.CategoryViewModel", "LoaiMonAn")
                        .WithMany()
                        .HasForeignKey("IDLOAIMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.SizeViewModel", "Size")
                        .WithMany()
                        .HasForeignKey("IDSIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.ProductsViewModel", null)
                        .WithMany("ListGiaSizes")
                        .HasForeignKey("ProductsViewModelIDMONAN");

                    b.HasOne("WebsiteOrdering.ViewModels.SizeViewModel", null)
                        .WithMany("ListGiaSize")
                        .HasForeignKey("SizeViewModelIDSIZE");

                    b.Navigation("LoaiMonAn");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ProductsViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.CategoryViewModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IDLoaiMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ToppingViewModel", b =>
                {
                    b.HasOne("WebsiteOrdering.ViewModels.CategoryViewModel", null)
                        .WithMany("Topping")
                        .HasForeignKey("CategoryViewModelIDLOAIMONAN");

                    b.HasOne("WebsiteOrdering.ViewModels.CategoryViewModel", "IdLoaiMonAn")
                        .WithMany()
                        .HasForeignKey("IDLOAIMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.ViewModels.ProductsViewModel", null)
                        .WithMany("Toppings")
                        .HasForeignKey("ProductsViewModelIDMONAN");

                    b.Navigation("IdLoaiMonAn");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.CategoryViewModel", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.DonHangViewModel", b =>
                {
                    b.Navigation("chitietdh");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.ProductsViewModel", b =>
                {
                    b.Navigation("ListGiaSizes");

                    b.Navigation("Toppings");
                });

            modelBuilder.Entity("WebsiteOrdering.ViewModels.SizeViewModel", b =>
                {
                    b.Navigation("ListGiaSize");
                });
#pragma warning restore 612, 618
        }
    }
}
