// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteOrdering.Data;

#nullable disable

namespace WebsiteOrdering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609104026_FullName")]
    partial class FullName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChitietdonhangTopping", b =>
                {
                    b.Property<string>("Idtopping")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Iddonhang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Idmonan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Idmonan2")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Idtopping", "Iddonhang", "Idmonan", "Idmonan2");

                    b.ToTable("ChitietdonhangTopping");
                });

            modelBuilder.Entity("ChitietdonhangonlTopping", b =>
                {
                    b.Property<string>("Idtopping")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Iddonhangonl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Idmonan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Idmonan2")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Idtopping", "Iddonhangonl", "Idmonan", "Idmonan2");

                    b.ToTable("ChitietdonhangonlTopping");
                });

            modelBuilder.Entity("Chitiettopping", b =>
                {
                    b.Property<string>("Idtopping")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDTOPPING")
                        .IsFixedLength();

                    b.Property<string>("Iddonhang")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANG")
                        .IsFixedLength();

                    b.Property<string>("Idmonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idmonan2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN2")
                        .IsFixedLength();

                    b.HasKey("Idtopping", "Iddonhang", "Idmonan", "Idmonan2")
                        .HasName("PK__CHITIETT__799084CEE74352D4");

                    b.HasIndex("Iddonhang", "Idmonan", "Idmonan2");

                    b.ToTable("CHITIETTOPPING", (string)null);
                });

            modelBuilder.Entity("Chitiettoppingonl", b =>
                {
                    b.Property<string>("Idtopping")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDTOPPING")
                        .IsFixedLength();

                    b.Property<string>("Iddonhangonl")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANGONL")
                        .IsFixedLength();

                    b.Property<string>("Idmonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idmonan2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN2")
                        .IsFixedLength();

                    b.HasKey("Idtopping", "Iddonhangonl", "Idmonan", "Idmonan2")
                        .HasName("PK__CHITIETT__AC0BDD50F7A79B3B");

                    b.HasIndex("Iddonhangonl", "Idmonan", "Idmonan2");

                    b.ToTable("CHITIETTOPPINGONL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Idchinhanh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Idchinhanh");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Ban", b =>
                {
                    b.Property<string>("Idban")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDBAN")
                        .IsFixedLength();

                    b.Property<string>("Idchinhanh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH")
                        .IsFixedLength();

                    b.Property<string>("Khuvuc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KHUVUC");

                    b.Property<int>("Songuoi")
                        .HasColumnType("int")
                        .HasColumnName("SONGUOI");

                    b.Property<string>("Tenban")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENBAN");

                    b.HasKey("Idban")
                        .HasName("PK__BAN__9367225EC3E6D028");

                    b.HasIndex("Idchinhanh");

                    b.ToTable("BAN");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chinhanh", b =>
                {
                    b.Property<string>("Idchinhanh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH")
                        .IsFixedLength();

                    b.Property<string>("Diachicn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHICN");

                    b.Property<string>("Tenchinhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENCHINHANH");

                    b.HasKey("Idchinhanh")
                        .HasName("PK__CHINHANH__5F20FC4041DF698B");

                    b.ToTable("CHINHANH");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietban", b =>
                {
                    b.Property<string>("Iddatban")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDATBAN")
                        .IsFixedLength();

                    b.Property<string>("Idban")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDBAN")
                        .IsFixedLength();

                    b.Property<TimeOnly>("Giora")
                        .HasColumnType("time")
                        .HasColumnName("GIORA");

                    b.Property<TimeOnly>("Giovao")
                        .HasColumnType("time")
                        .HasColumnName("GIOVAO");

                    b.Property<string>("Trangthaiban")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAIBAN");

                    b.HasKey("Iddatban", "Idban")
                        .HasName("PK__CHITIETB__27F2122C9119BD2E");

                    b.HasIndex("Idban");

                    b.ToTable("CHITIETBAN");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietdonhang", b =>
                {
                    b.Property<string>("Iddonhang")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANG")
                        .IsFixedLength();

                    b.Property<string>("Idmonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idmonan2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN2")
                        .IsFixedLength();

                    b.Property<string>("Ghichu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHICHU");

                    b.Property<int>("Gia")
                        .HasColumnType("int")
                        .HasColumnName("GIA");

                    b.Property<string>("Iddebanh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDEBANH")
                        .IsFixedLength();

                    b.Property<string>("Idsize")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDSIZE")
                        .IsFixedLength();

                    b.Property<string>("Kieupizza")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KIEUPIZZA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<int>("Tongtien")
                        .HasColumnType("int")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("Iddonhang", "Idmonan", "Idmonan2")
                        .HasName("PK__CHITIETD__8EFDF8BDABAA408C");

                    b.HasIndex("Iddebanh");

                    b.HasIndex("Idsize");

                    b.HasIndex("Idmonan", "Idmonan2");

                    b.ToTable("CHITIETDONHANG");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietdonhangonl", b =>
                {
                    b.Property<string>("Iddonhangonl")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANGONL")
                        .IsFixedLength();

                    b.Property<string>("Idmonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idmonan2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN2")
                        .IsFixedLength();

                    b.Property<string>("Ghichu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHICHU");

                    b.Property<int>("Giadh")
                        .HasColumnType("int")
                        .HasColumnName("GIADH");

                    b.Property<string>("Iddebanh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDEBANH")
                        .IsFixedLength();

                    b.Property<string>("Idsize")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDSIZE")
                        .IsFixedLength();

                    b.Property<string>("Kieupizzaonl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KIEUPIZZAONL");

                    b.Property<int>("Soluongdh")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGDH");

                    b.Property<int>("Tongtiendh")
                        .HasColumnType("int")
                        .HasColumnName("TONGTIENDH");

                    b.HasKey("Iddonhangonl", "Idmonan", "Idmonan2")
                        .HasName("PK__CHITIETD__D7486150E300646B");

                    b.HasIndex("Iddebanh");

                    b.HasIndex("Idsize");

                    b.HasIndex("Idmonan", "Idmonan2");

                    b.ToTable("CHITIETDONHANGONL");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Danhmuckhuyenmai", b =>
                {
                    b.Property<string>("Idkhuyenmai")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDKHUYENMAI")
                        .IsFixedLength();

                    b.Property<int>("Giatri")
                        .HasColumnType("int")
                        .HasColumnName("GIATRI");

                    b.Property<string>("Motakm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MOTAKM");

                    b.Property<DateOnly>("Ngayapdung")
                        .HasColumnType("date")
                        .HasColumnName("NGAYAPDUNG");

                    b.Property<DateOnly>("Ngayhethan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYHETHAN");

                    b.Property<string>("Tenkhuyenmai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENKHUYENMAI");

                    b.HasKey("Idkhuyenmai")
                        .HasName("PK__DANHMUCK__9E055897C118320B");

                    b.ToTable("DANHMUCKHUYENMAI");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Datban", b =>
                {
                    b.Property<string>("Iddatban")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDATBAN")
                        .IsFixedLength();

                    b.Property<string>("Ghichu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHICHU");

                    b.Property<TimeOnly>("Giobatdau")
                        .HasColumnType("time")
                        .HasColumnName("GIOBATDAU");

                    b.Property<TimeOnly>("Gioketthuc")
                        .HasColumnType("time")
                        .HasColumnName("GIOKETTHUC");

                    b.Property<string>("Idchinhanh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH")
                        .IsFixedLength();

                    b.Property<DateOnly>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDAT");

                    b.Property<int>("Songuoidat")
                        .HasColumnType("int")
                        .HasColumnName("SONGUOIDAT");

                    b.Property<string>("Trangthaidatban")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAIDATBAN");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Iddatban")
                        .HasName("PK__DATBAN__DEC46009C032B7D1");

                    b.HasIndex("Idchinhanh");

                    b.HasIndex("UserId");

                    b.ToTable("DATBAN");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Debanh", b =>
                {
                    b.Property<string>("Iddebanh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDEBANH")
                        .IsFixedLength();

                    b.Property<int>("Giadebanh")
                        .HasColumnType("int")
                        .HasColumnName("GIADEBANH");

                    b.Property<string>("Tendebanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDEBANH");

                    b.HasKey("Iddebanh")
                        .HasName("PK__DEBANH__555F23FFB140968E");

                    b.ToTable("DEBANH");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhang", b =>
                {
                    b.Property<string>("Iddonhang")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANG")
                        .IsFixedLength();

                    b.Property<string>("Idchinhanh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH")
                        .IsFixedLength();

                    b.Property<string>("Iddatban")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDATBAN")
                        .IsFixedLength();

                    b.Property<string>("Idkhuyenmai")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDKHUYENMAI")
                        .IsFixedLength();

                    b.Property<DateOnly>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDAT");

                    b.Property<string>("Phuongthucthanhtoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHUONGTHUCTHANHTOAN");

                    b.Property<int>("Songuoi")
                        .HasColumnType("int")
                        .HasColumnName("SONGUOI");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKH");

                    b.Property<int>("Tongdh")
                        .HasColumnType("int")
                        .HasColumnName("TONGDH");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Iddonhang")
                        .HasName("PK__DONHANG__F59FA8B118A5D193");

                    b.HasIndex("Idchinhanh");

                    b.HasIndex("Iddatban");

                    b.HasIndex("Idkhuyenmai");

                    b.HasIndex("UserId");

                    b.ToTable("DONHANG");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhangonl", b =>
                {
                    b.Property<string>("Iddonhangonl")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDDONHANGONL")
                        .IsFixedLength();

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Idchinhanh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDCHINHANH")
                        .IsFixedLength();

                    b.Property<string>("Idkhuyenmai")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDKHUYENMAI")
                        .IsFixedLength();

                    b.Property<DateOnly>("Ngaydatdon")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDATDON");

                    b.Property<string>("Ptttonl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PTTTONL");

                    b.Property<int>("Tienship")
                        .HasColumnType("int")
                        .HasColumnName("TIENSHIP");

                    b.Property<int>("Tongtien")
                        .HasColumnType("int")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Iddonhangonl")
                        .HasName("PK__DONHANGO__AC2A315C15B12C03");

                    b.HasIndex("Idchinhanh");

                    b.HasIndex("Idkhuyenmai");

                    b.HasIndex("UserId");

                    b.ToTable("DONHANGONL");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Listgiasize", b =>
                {
                    b.Property<string>("Idloaimonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDLOAIMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idsize")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDSIZE")
                        .IsFixedLength();

                    b.Property<int>("Gia")
                        .HasColumnType("int")
                        .HasColumnName("GIA");

                    b.HasKey("Idloaimonan", "Idsize")
                        .HasName("PK__LISTGIAS__93A480291F324B05");

                    b.HasIndex("Idsize");

                    b.ToTable("LISTGIASIZE");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Loaimonan", b =>
                {
                    b.Property<string>("Idloaimonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDLOAIMONAN")
                        .IsFixedLength();

                    b.Property<string>("Tenloaimonan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAIMONAN");

                    b.HasKey("Idloaimonan")
                        .HasName("PK__LOAIMONA__6B7E94ED8043D23A");

                    b.ToTable("LOAIMONAN");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .IsFixedLength();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ID__6B7E94ED8043D11B");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Monan", b =>
                {
                    b.Property<string>("Idmonan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN")
                        .IsFixedLength();

                    b.Property<string>("Idmonan2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDMONAN2")
                        .IsFixedLength();

                    b.Property<string>("Anhmonan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ANHMONAN");

                    b.Property<int>("Giacoban")
                        .HasColumnType("int")
                        .HasColumnName("GIACOBAN");

                    b.Property<string>("Idloaimonan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDLOAIMONAN")
                        .IsFixedLength();

                    b.Property<string>("Motamonan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MOTAMONAN");

                    b.Property<string>("Tenmonan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TENMONAN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Idmonan", "Idmonan2")
                        .HasName("PK__MONAN__B62500C613AC53C3");

                    b.HasIndex("Idloaimonan");

                    b.ToTable("MONAN");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Size", b =>
                {
                    b.Property<string>("Idsize")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDSIZE")
                        .IsFixedLength();

                    b.Property<string>("Tensize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSIZE");

                    b.HasKey("Idsize")
                        .HasName("PK__SIZE__8DA14C4E58CC03AA");

                    b.ToTable("SIZE");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Topping", b =>
                {
                    b.Property<string>("Idtopping")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDTOPPING")
                        .IsFixedLength();

                    b.Property<int>("Giatopping")
                        .HasColumnType("int")
                        .HasColumnName("GIATOPPING");

                    b.Property<string>("Idloaimonan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("IDLOAIMONAN")
                        .IsFixedLength();

                    b.Property<string>("Tentopping")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTOPPING");

                    b.HasKey("Idtopping")
                        .HasName("PK__TOPPING__B17F5B459FE8393F");

                    b.HasIndex("Idloaimonan");

                    b.ToTable("TOPPING");
                });

            modelBuilder.Entity("Chitiettopping", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Topping", null)
                        .WithMany()
                        .HasForeignKey("Idtopping")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETTO__IDTOP__151B244E");

                    b.HasOne("WebsiteOrdering.Models.Entities.Chitietdonhang", null)
                        .WithMany()
                        .HasForeignKey("Iddonhang", "Idmonan", "Idmonan2")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETTOPPING__160F4887");
                });

            modelBuilder.Entity("Chitiettoppingonl", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Topping", null)
                        .WithMany()
                        .HasForeignKey("Idtopping")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETTO__IDTOP__18EBB532");

                    b.HasOne("WebsiteOrdering.Models.Entities.Chitietdonhangonl", null)
                        .WithMany()
                        .HasForeignKey("Iddonhangonl", "Idmonan", "Idmonan2")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETTOPPINGON__19DFD96B");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebsiteOrdering.Models.ApplicationUser", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Chinhanh", "IdchinhanhNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Idchinhanh");

                    b.Navigation("IdchinhanhNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Ban", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Chinhanh", "IdchinhanhNavigation")
                        .WithMany("Bans")
                        .HasForeignKey("Idchinhanh")
                        .IsRequired()
                        .HasConstraintName("FK__BAN__IDCHINHANH__6477ECF3");

                    b.Navigation("IdchinhanhNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietban", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Ban", "IdbanNavigation")
                        .WithMany("Chitietbans")
                        .HasForeignKey("Idban")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETBA__IDBAN__76969D2E");

                    b.HasOne("WebsiteOrdering.Models.Entities.Datban", "IddatbanNavigation")
                        .WithMany("Chitietbans")
                        .HasForeignKey("Iddatban")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETBA__IDDAT__75A278F5");

                    b.Navigation("IdbanNavigation");

                    b.Navigation("IddatbanNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietdonhang", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Debanh", "IddebanhNavigation")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Iddebanh")
                        .HasConstraintName("FK__CHITIETDO__IDDEB__0A9D95DB");

                    b.HasOne("WebsiteOrdering.Models.Entities.Donhang", "IddonhangNavigation")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Iddonhang")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__IDDON__09A971A2");

                    b.HasOne("WebsiteOrdering.Models.Entities.Size", "IdsizeNavigation")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Idsize")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__IDSIZ__0C85DE4D");

                    b.HasOne("WebsiteOrdering.Models.Entities.Monan", "Monan")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Idmonan", "Idmonan2")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDONHANG__0B91BA14");

                    b.Navigation("IddebanhNavigation");

                    b.Navigation("IddonhangNavigation");

                    b.Navigation("IdsizeNavigation");

                    b.Navigation("Monan");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chitietdonhangonl", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Debanh", "IddebanhNavigation")
                        .WithMany("Chitietdonhangonls")
                        .HasForeignKey("Iddebanh")
                        .HasConstraintName("FK__CHITIETDO__IDDEB__10566F31");

                    b.HasOne("WebsiteOrdering.Models.Entities.Donhangonl", "IddonhangonlNavigation")
                        .WithMany("Chitietdonhangonls")
                        .HasForeignKey("Iddonhangonl")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__IDDON__0F624AF8");

                    b.HasOne("WebsiteOrdering.Models.Entities.Size", "IdsizeNavigation")
                        .WithMany("Chitietdonhangonls")
                        .HasForeignKey("Idsize")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__IDSIZ__114A936A");

                    b.HasOne("WebsiteOrdering.Models.Entities.Monan", "Monan")
                        .WithMany("Chitietdonhangonls")
                        .HasForeignKey("Idmonan", "Idmonan2")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDONHANGON__123EB7A3");

                    b.Navigation("IddebanhNavigation");

                    b.Navigation("IddonhangonlNavigation");

                    b.Navigation("IdsizeNavigation");

                    b.Navigation("Monan");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Datban", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Chinhanh", "IdchinhanhNavigation")
                        .WithMany("Datbans")
                        .HasForeignKey("Idchinhanh")
                        .IsRequired()
                        .HasConstraintName("FK__DATBAN__IDCHINHA__60A75C0F");

                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", "User")
                        .WithMany("Datbans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__DATBAN__USERID__619B8048");

                    b.Navigation("IdchinhanhNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhang", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Chinhanh", "IdchinhanhNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Idchinhanh")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__IDCHINH__7C4F7684");

                    b.HasOne("WebsiteOrdering.Models.Entities.Datban", "IddatbanNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Iddatban")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__IDDATBA__7E37BEF6");

                    b.HasOne("WebsiteOrdering.Models.Entities.Danhmuckhuyenmai", "IdkhuyenmaiNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Idkhuyenmai")
                        .HasConstraintName("FK__DONHANG__IDKHUYE__7F2BE32F");

                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", "User")
                        .WithMany("Donhangs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__USERID__7D439ABD");

                    b.Navigation("IdchinhanhNavigation");

                    b.Navigation("IddatbanNavigation");

                    b.Navigation("IdkhuyenmaiNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhangonl", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Chinhanh", "IdchinhanhNavigation")
                        .WithMany("Donhangonls")
                        .HasForeignKey("Idchinhanh")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANGON__IDCHI__02FC7413");

                    b.HasOne("WebsiteOrdering.Models.Entities.Danhmuckhuyenmai", "IdkhuyenmaiNavigation")
                        .WithMany("Donhangonls")
                        .HasForeignKey("Idkhuyenmai")
                        .HasConstraintName("FK__DONHANGON__IDKHU__03F0984C");

                    b.HasOne("WebsiteOrdering.Models.ApplicationUser", "User")
                        .WithMany("Donhangonls")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANGONL__USERID__02084FDA");

                    b.Navigation("IdchinhanhNavigation");

                    b.Navigation("IdkhuyenmaiNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Listgiasize", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Loaimonan", "IdloaimonanNavigation")
                        .WithMany("Listgiasizes")
                        .HasForeignKey("Idloaimonan")
                        .IsRequired()
                        .HasConstraintName("FK__LISTGIASI__IDLOA__71D1E811");

                    b.HasOne("WebsiteOrdering.Models.Entities.Size", "IdsizeNavigation")
                        .WithMany("Listgiasizes")
                        .HasForeignKey("Idsize")
                        .IsRequired()
                        .HasConstraintName("FK__LISTGIASI__IDSIZ__72C60C4A");

                    b.Navigation("IdloaimonanNavigation");

                    b.Navigation("IdsizeNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Monan", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Loaimonan", "IdloaimonanNavigation")
                        .WithMany("Monans")
                        .HasForeignKey("Idloaimonan")
                        .IsRequired()
                        .HasConstraintName("FK__MONAN__IDLOAIMON__06CD04F7");

                    b.Navigation("IdloaimonanNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Topping", b =>
                {
                    b.HasOne("WebsiteOrdering.Models.Entities.Loaimonan", "IdloaimonanNavigation")
                        .WithMany("Toppings")
                        .HasForeignKey("Idloaimonan")
                        .IsRequired()
                        .HasConstraintName("FK__TOPPING__IDLOAIM__6B24EA82");

                    b.Navigation("IdloaimonanNavigation");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.ApplicationUser", b =>
                {
                    b.Navigation("Datbans");

                    b.Navigation("Donhangonls");

                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Ban", b =>
                {
                    b.Navigation("Chitietbans");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Chinhanh", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Datbans");

                    b.Navigation("Donhangonls");

                    b.Navigation("Donhangs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Danhmuckhuyenmai", b =>
                {
                    b.Navigation("Donhangonls");

                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Datban", b =>
                {
                    b.Navigation("Chitietbans");

                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Debanh", b =>
                {
                    b.Navigation("Chitietdonhangonls");

                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhang", b =>
                {
                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Donhangonl", b =>
                {
                    b.Navigation("Chitietdonhangonls");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Loaimonan", b =>
                {
                    b.Navigation("Listgiasizes");

                    b.Navigation("Monans");

                    b.Navigation("Toppings");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Monan", b =>
                {
                    b.Navigation("Chitietdonhangonls");

                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("WebsiteOrdering.Models.Entities.Size", b =>
                {
                    b.Navigation("Chitietdonhangonls");

                    b.Navigation("Chitietdonhangs");

                    b.Navigation("Listgiasizes");
                });
#pragma warning restore 612, 618
        }
    }
}
